---
title: "Análisis de los empleados de Baltimore"
author: "Úrsula Casaus Fabra"
date: "2024-02-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Borra todas las variables

rm(list = ls())
```

# Ruta del fichero

```{r}
RutaFichero = "data/Baltimore_City_Employee_Salaries.csv"
```


# Importamos datos con Rbase

```{r}
datos_rbase <- read.csv(file = RutaFichero)
datos_rbase
```

# Importamos datos con Readr

```{r}
datos_readr <- read_csv(RutaFichero, col_types = cols(hireDate = 
                                              col_date(format = "%Y-%m-%d")))
datos_readr
```

# Importamos datos con librería RIO

```{r}
library(rio)
datos_rio <- import(RutaFichero)
datos_rio
```

# Leemos el fichero línea a línea

```{r}
lineas_leidas <- readLines("data/Baltimore_City_Employee_Salaries.csv")

# Revisamos la codificación del fichero

guess_encoding(RutaFichero)

# Leemos con la codificación adecuada

f <- file(RutaFichero, encoding = "UTF-8")

datosLineas <- readLines(con = f) # Lo ponemos para asociarlo con el fichero
```

# Miramos la codificación del fichero

```{r}
guess_encoding("empleados.Rmd")
```

# Nos conectamos a la base de datos

```{r}
library("RMySQL")

#Conexión
mysqlconnection = dbConnect(RMySQL::MySQL(), dbname='employees', host='oceano.uv.es',
port=3306, user='datamecum',password='ford')
#Información
dbGetInfo(mysqlconnection)
# Tablas contenidas en la BBDD
dbListTables(mysqlconnection)
# Descarga de tablas --> data.frame
salarios<-dbReadTable(mysqlconnection,name = 'salaries')
empleados<-dbReadTable(mysqlconnection,name = 'employees')
# Realizamos una consulta SQL en la BBDD (sin descargar)
result = dbSendQuery(mysqlconnection, "select * from employees")
# Descargamos los n (5) elementos resultantes de la consulta
data.frame = dbFetch(result, n = 5)
# Librera y finaliza la consulta
dbClearResult(result)
```

